### PR TITLE
DO NOT MERGE: Validator for size check CI job.

### PR DESCRIPTION
**Pull request by brizental**
This is here just to check that the CI job actually works.

### CODE REVIEW

**Comment by moz-glean** [comment]
# Build size report

Merging https://github.com/mozilla/glean.js/pull/423 into [main](https://github.com/mozilla/glean.js) will:
* **Increase** the size of full **Web Extension** bundle build by `20%`.
* **Increase** the size of full **Qt/QML** bundle build by `14%`.

---

| | Current size | New size | Size increase |
|--:|:---:|:---:|:---:|
| **Web Extension** |
| core only | 44 KB | 58 KB | 📈 14 KB |
| full bundle | 67 KB | 80 KB | 📈 14 KB |
| **Qt/QML** |
| core only | 95 KB | 109 KB | 📈 14 KB |
| full bundle | 95 KB | 109 KB | 📈 14 KB |

**Comment by moz-glean** [comment]
# Build size report

Merging https://github.com/mozilla/glean.js/pull/423 into [main](https://github.com/mozilla/glean.js) will:
* **Increase** the size of full **Web Extension** bundle build by `20%`.
* **Increase** the size of full **Qt/QML** bundle build by `14%`.

---

| | Current size | New size | Size increase |
|--:|:---:|:---:|:---:|
| **Web Extension** |
| core only | 44 KB | 58 KB | 📈 14 KB |
| full bundle | 67 KB | 80 KB | 📈 14 KB |
| **Qt/QML** |
| core only | 95 KB | 109 KB | 📈 14 KB |
| full bundle | 95 KB | 109 KB | 📈 14 KB |

**Comment by moz-glean** [comment]
# Build size report

Merging https://github.com/mozilla/glean.js/pull/423 into [main](https://github.com/mozilla/glean.js) will:
* **Increase** the size of full **Web Extension** bundle build by `20%`.
* **Increase** the size of full **Qt/QML** bundle build by `14%`.

---

| | Current size | New size | Size increase |
|--:|:---:|:---:|:---:|
| **Web Extension** |
| core only | 44 KB | 58 KB | 📈 14 KB |
| full bundle | 67 KB | 80 KB | 📈 14 KB |
| **Qt/QML** |
| core only | 95 KB | 109 KB | 📈 14 KB |
| full bundle | 95 KB | 109 KB | 📈 14 KB |

**Comment by brizental** [comment]
Closing because this got stale.

**Pull request closed without merging**
